# Change these first
owner: tamus-cyber # Your GitHub organization or username, where this repository lives
repo: status.cyber.tamus.edu # The name of this repository

sites:
  - name: TAMUS Cyber Website
    url: https://www.cyber.tamus.edu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cyber.tamus.edu
  # baseUrl: /your-repo-name
  logoUrl: https://www.cyber.tamus.edu/img/tamus-cyber-logo.svg
  # name: TAMUS Cyber Status
  introTitle: "**TAMUS Cyber Status** is based on Upptime, the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.cyber.tamus.edu/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
